title = 'Liam Blogs'
baseURL = 'https://lamthanhnguyen.github.io/'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

languageCode = 'en-us'
enableRobotsTXT = true

[pagination]
pagerSize = 10

[params]
favicon = "/images/favicon_logo.webp"
recent_posts_number = 5
custom_css = ["css/custom.css"]

[params.ananke.social.share]
networks = [
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "linkedin"
]

[params.ananke.social.linkedin]
username = "lam-thanh-nguyen-abcd6789"

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'